In [27]:
import pandas as pd 
import numpy as np

In [28]:
df = pd.read_csv('../data/health_index.csv')

In [29]:
df.head()

,Hydrogen,Oxigen,Nitrogen,Methane,CO,CO2,Ethylene,Ethane,Acethylene,DBDS,Power factor,Interfacial V,Dielectric rigidity,Water content,Health index,Life expectation
0,2845,5860,27842,7406,32,1344,16684,5467,7,19.0,1.00,45,55,0,95.2,19.0
1,12886,61,25041,877,83,864,4,305,0,45.0,1.00,45,55,0,85.5,19.0
2,2820,16400,56300,144,257,1080,206,11,2190,1.0,1.00,39,52,11,85.3,19.0
3,1099,70,37520,545,184,1402,6,230,0,87.0,4.58,33,49,5,85.3,6.0
4,3210,3570,47900,160,360,2130,4,43,4,1.0,0.77,44,55,3,85.2,6.0

In [ ]:
# df = df[~df["Life expectation"].round(1).isin([40.8, 42.5])]
# df["Life expectation"].isin([40.8, 42.5]).sum()

0

In [31]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [32]:
# X_LE.shape

In [33]:
scaler_X_LE = MinMaxScaler()
scaler_y_LE = MinMaxScaler()

In [34]:
X_LE = df.iloc[:,:15]

In [35]:
X_LE

,Hydrogen,Oxigen,Nitrogen,Methane,CO,CO2,Ethylene,Ethane,Acethylene,DBDS,Power factor,Interfacial V,Dielectric rigidity,Water content,Health index
0,2845,5860,27842,7406,32,1344,16684,5467,7,19.0,1.00,45,55,0,95.2
1,12886,61,25041,877,83,864,4,305,0,45.0,1.00,45,55,0,85.5
2,2820,16400,56300,144,257,1080,206,11,2190,1.0,1.00,39,52,11,85.3
3,1099,70,37520,545,184,1402,6,230,0,87.0,4.58,33,49,5,85.3
4,3210,3570,47900,160,360,2130,4,43,4,1.0,0.77,44,55,3,85.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
465,15,227,52900,3,60,853,3,84,0,0.0,1.00,32,56,28,13.4
466,15,334,47100,3,64,622,3,108,0,0.0,1.00,32,55,12,13.4
467,15,1280,35000,2,675,2530,0,0,0,5.0,0.30,45,58,8,13.4
468,15,169,50600,5,77,532,0,72,0,0.0,1.21,33,54,11,13.4
469,15,308,39700,3,64,581,5,27,0,0.0,1.00,32,60,18,13.4

In [36]:
# X_LE['Health Index'] = df.iloc[:,-2]

In [37]:
X_LE = X_LE.values

In [38]:
X_LE

array([[2.8450e+03, 5.8600e+03, 2.7842e+04, ..., 5.5000e+01, 0.0000e+00,
        9.5200e+01],
       [1.2886e+04, 6.1000e+01, 2.5041e+04, ..., 5.5000e+01, 0.0000e+00,
        8.5500e+01],
       [2.8200e+03, 1.6400e+04, 5.6300e+04, ..., 5.2000e+01, 1.1000e+01,
        8.5300e+01],
       ...,
       [1.5000e+01, 1.2800e+03, 3.5000e+04, ..., 5.8000e+01, 8.0000e+00,
        1.3400e+01],
       [1.5000e+01, 1.6900e+02, 5.0600e+04, ..., 5.4000e+01, 1.1000e+01,
        1.3400e+01],
       [1.5000e+01, 3.0800e+02, 3.9700e+04, ..., 6.0000e+01, 1.8000e+01,
        1.3400e+01]])

In [39]:
y_LE = df.iloc[:,-1].values
y_LE = y_LE.reshape(-1,1)

In [40]:
y_LE.shape

(468, 1)

In [41]:
X_LE = scaler_X_LE.fit_transform(X_LE)
y_LE = scaler_y_LE.fit_transform(y_LE)

In [42]:
X_LE

array([[1.21846760e-01, 2.32265863e-02, 2.96719706e-01, ...,
        5.83333333e-01, 0.00000000e+00, 1.00000000e+00],
       [5.51886590e-01, 1.60100543e-05, 2.62435741e-01, ...,
        5.83333333e-01, 0.00000000e+00, 8.81418093e-01],
       [1.20776050e-01, 6.54130794e-02, 6.45042840e-01, ...,
        5.20833333e-01, 6.01092896e-02, 8.78973105e-01],
       ...,
       [6.42425800e-04, 4.89507411e-03, 3.84332925e-01, ...,
        6.45833333e-01, 4.37158470e-02, 0.00000000e+00],
       [6.42425800e-04, 4.48281521e-04, 5.75275398e-01, ...,
        5.62500000e-01, 6.01092896e-02, 0.00000000e+00],
       [6.42425800e-04, 1.00463091e-03, 4.41860465e-01, ...,
        6.87500000e-01, 9.83606557e-02, 0.00000000e+00]])

In [43]:
y_LE

array([[0.28888889],
       [0.28888889],
       [0.28888889],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.28888889],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.28888889],
       [0.28888889],
       [0.28888889],
       [0.28888889],
       [0.28888889],
       [0.28888889],
       [0.28888889],
       [0.02      ],
       [0.28888889],
       [0.        ],
       [0.00222222],
       [0.00222222],
       [0.25555556],
       [0.03111111],
       [0.31777778],
       [0.01111111],
       [0.01333333],
       [0.20444444],
       [0.51333333],
       [0.51333333],
       [0.51333333],
       [0.01111111],
       [0.52888889],
       [0.23111111],
       [0.52888889],
       [0.52888889],
       [0.52888889],
       [0.52888889],
       [0.52888889],
       [0.52888889],
       [0.52888889],
       [0.52888889],
       [0.52888889],
       [0.52888889],
       [0.53111111],
       [0.53111111],
       [0.53333333],
       [0.53777778],
       [0.54      ],
       [0.25111111],
       [0.25333333],
       [0.25333333],
       [0.25555556],
       [0.25555556],
       [0.25777778],
       [0.26      ],
       [0.00222222],
       [0.01111111],
       [0.26444444],
       [0.01111111],
       [0.26444444],
       [0.00222222],
       [0.26444444],
       [0.26444444],
       [0.26444444],
       [0.01111111],
       [0.01111111],
       [0.01111111],
       [0.26444444],
       [0.26222222],
       [0.26444444],
       [0.01111111],
       [0.01111111],
       [0.55777778],
       [0.55777778],
       [0.26444444],
       [0.01111111],
       [0.01111111],
       [0.01111111],
       [0.55777778],
       [0.01111111],
       [0.01111111],
       [0.01111111],
       [0.01111111],
       [0.01111111],
       [0.26      ],
       [0.01111111],
       [0.01111111],
       [0.01111111],
       [0.55777778],
       [0.26444444],
       [0.26444444],
       [0.26444444],
       [0.26444444],
       [0.26444444],
       [0.26444444],
       [0.26444444],
       [0.26      ],
       [0.55777778],
       [0.01111111],
       [0.01111111],
       [0.01111111],
       [0.26444444],
       [0.26444444],
       [0.55777778],
       [0.55777778],
       [0.01111111],
       [0.01111111],
       [0.01111111],
       [0.01111111],
       [0.56222222],
       [0.04      ],
       [0.28444444],
       [0.57777778],
       [0.57777778],
       [0.57777778],
       [0.57777778],
       [0.58      ],
       [0.57777778],
       [0.28888889],
       [0.28888889],
       [0.28888889],
       [0.29111111],
       [0.57777778],
       [0.29111111],
       [0.57777778],
       [0.28888889],
       [0.57777778],
       [0.57777778],
       [0.29111111],
       [0.57777778],
       [0.57777778],
       [0.01111111],
       [0.28888889],
       [0.57777778],
       [0.57777778],
       [0.57777778],
       [0.57777778],
       [0.01111111],
       [0.01111111],
       [0.28888889],
       [0.57777778],
       [0.28888889],
       [0.57777778],
       [0.57777778],
       [0.57777778],
       [0.28888889],
       [0.28888889],
       [0.00444444],
       [0.00222222],
       [0.01111111],
       [0.28888889],
       [0.28888889],
       [0.57777778],
       [0.28888889],
       [0.28888889],
       [0.01111111],
       [0.29111111],
       [0.57777778],
       [0.57777778],
       [0.57777778],
       [0.28888889],
       [0.57777778],
       [0.28888889],
       [0.57777778],
       [0.57777778],
       [0.28888889],
       [0.01111111],
       [0.28888889],
       [0.57777778],
       [0.57777778],
       [0.29111111],
       [0.01111111],
       [0.01111111],
       [0.57777778],
       [0.57777778],
       [0.57777778],
       [0.01111111],
       [0.28888889],
       [0.57777778],
       [0.01333333],
       [0.00222222],
       [0.99333333],
       [0.30666667],
       [0.99333333],
       [0.30444444],
       [0.99333333],
       [0.99333333],
       [0.01111111],
       [0.99333333],
       [0.99333333],
       [0.99333333],
       [0.62      ],
       [0.99555556],
       [0.99555556],
       [0.99555556],
       [0.99555556],
       [1.        ],
       [1.        ],
       [1.        ],
       [0.01111111],
       [0.01111111],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [0.28888889],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [0.28888889],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [0.60888889],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [0.57777778],
       [1.        ],
       [1.        ],
       [1.        ],
       [0.01111111],
       [0.01111111],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [0.01111111],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [0.01111111],
       [1.        ],
       [0.28888889],
       [1.        ],
       [0.28888889],
       [0.28888889],
       [0.28888889],
       [1.        ],
       [1.        ],
       [1.        ],
       [0.60888889],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [0.00222222],
       [1.        ],
       [1.        ],
       [0.01111111],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [0.00444444],
       [1.        ],
       [1.        ],
       [1.        ],
       [0.01111111],
       [1.        ],
       [0.28888889],
       [1.        ],
       [1.        ],
       [0.61333333],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [0.28888889],
       [0.29111111],
       [1.        ],
       [0.60888889],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [0.01111111],
       [0.28888889],
       [1.        ],
       [1.        ],
       [1.        ],
       [0.28888889],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [0.29111111],
       [1.        ],
       [0.28888889],
       [0.28888889],
       [0.28888889],
       [0.01111111],
       [0.28888889],
       [0.01111111],
       [0.29111111],
       [0.01111111],
       [1.        ],
       [1.        ],
       [0.01111111],
       [0.01111111],
       [0.01111111],
       [0.01111111],
       [0.01111111],
       [0.01111111],
       [0.28888889],
       [0.28888889],
       [0.28888889],
       [0.28888889],
       [0.58666667],
       [0.60888889],
       [0.60888889],
       [1.        ],
       [1.        ],
       [1.        ],
       [0.28888889],
       [0.28888889],
       [0.28888889],
       [0.28888889],
       [0.01111111],
       [0.28888889],
       [0.28888889],
       [0.01555556],
       [0.28888889],
       [1.        ],
       [1.        ],
       [0.28888889],
       [0.28888889],
       [0.28888889],
       [0.28888889],
       [0.28888889],
       [1.        ],
       [0.29111111],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [0.28888889],
       [0.28888889],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [0.28888889],
       [1.        ],
       [1.        ],
       [0.01111111],
       [1.        ],
       [1.        ]])

In [44]:
from sklearn.model_selection import train_test_split

In [45]:
X_train, X_test, y_train, y_test = train_test_split(X_LE, y_LE, test_size=0.15, random_state=42)

In [46]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [47]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization, Activation
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.metrics import classification_report, confusion_matrix

In [48]:
def assign_class(le):
    if 6 <= le <= 7.75:
        return 0
    elif 15 <= le <= 20:
        return 1
    elif 29 <= le <= 40:
        return 2
    elif 43 <= le <= 51:
        return 3
    else:
        return -1

y_raw = df.iloc[:, -1].values
X_raw = df.iloc[:, :15].values

labels = np.array([assign_class(v) for v in y_raw])

# Filter out rows that fall outside defined ranges
mask = labels != -1
X_cls = X_raw[mask]
y_cls = labels[mask]

print("Kept", mask.sum(), "samples, removed", (~mask).sum(), "outliers")
print("Class distribution:", np.bincount(y_cls))

Kept 466 samples, removed 2 outliers
Class distribution: [ 81 105  69 211]

In [51]:
unique, counts = np.unique(y_cls, return_counts=True)
print(dict(zip(unique, counts)))
print(class_weights)

{0: 81, 1: 105, 2: 69, 3: 211}
{0: 1.4382716049382716, 1: 1.1095238095238096, 2: 1.6884057971014492, 3: 0.5521327014218009}

In [57]:
y_cls = pd.qcut(df["Life expectation"], q=4, labels=False, duplicates='drop')
np.unique(y_cls, return_counts=True)

(array([0, 1, 2], dtype=int64), array([176,  72, 220], dtype=int64))

In [61]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler
from sklearn.model_selection import train_test_split
from sklearn.utils.class_weight import compute_class_weight
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, BatchNormalization, Dropout
from tensorflow.keras.callbacks import EarlyStopping

# ---------------------------
# 1. CLEAN + ALIGN DATA FIRST
# ---------------------------
# Ensure no NaNs in target
df = df.dropna(subset=["Life expectation"])

# Create classes
y_cls = pd.qcut(df["Life expectation"], q=4, labels=False, duplicates='drop')

# Remove rows where qcut failed
mask = ~y_cls.isna()
df = df.loc[mask]
y_cls = y_cls.loc[mask]

# Reset index to avoid alignment issues
df = df.reset_index(drop=True)
y_cls = y_cls.reset_index(drop=True)

# Features
X_cls = df.drop(columns=["Life expectation"])

# ---------------------------
# 2. BUILD MODEL
# ---------------------------
def build_model(input_dim, num_classes):
    m = Sequential([
        Dense(64, input_shape=(input_dim,), activation="relu"),
        BatchNormalization(),
        Dropout(0.3),

        Dense(32, activation="relu"),
        BatchNormalization(),

        Dense(num_classes, activation="softmax")
    ])
    m.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=0.0005),
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"]
    )
    return m

# ---------------------------
# 3. SCALERS
# ---------------------------
scalers = {
    "MinMax":   MinMaxScaler(),
    "Standard": StandardScaler(),
    "Robust":   RobustScaler(),
}

results = {}
es = EarlyStopping(monitor="val_loss", patience=15, restore_best_weights=True)

# ---------------------------
# 4. CLASS WEIGHTS (FIXED)
# ---------------------------
classes = np.unique(y_cls)
weights = compute_class_weight(class_weight='balanced', classes=classes, y=y_cls)
class_weights = dict(zip(classes, weights))

print("Class distribution:", dict(zip(*np.unique(y_cls, return_counts=True))))
print("Class weights:", class_weights)

# ---------------------------
# 5. TRAIN LOOP
# ---------------------------
for name, scaler in scalers.items():

    # Fit scaler ONLY on X
    X_scaled = scaler.fit_transform(X_cls)

    # Split (now safe)
    X_tr, X_te, y_tr, y_te = train_test_split(
        X_scaled, y_cls, test_size=0.15, random_state=42, stratify=y_cls
    )

    tf.random.set_seed(42)

    m = build_model(input_dim=X_tr.shape[1], num_classes=len(classes))

    m.fit(
        X_tr, y_tr,
        epochs=150,
        batch_size=32,
        validation_split=0.15,
        verbose=0,
        callbacks=[es],
        class_weight=class_weights
    )

    _, acc = m.evaluate(X_te, y_te, verbose=0)

    results[name] = {
        "scaler": scaler,
        "model": m,
        "X_test": X_te,
        "y_test": y_te,
        "acc": acc
    }

    print(f"{name:10s}  test accuracy: {acc:.4f}")

# ---------------------------
# 6. BEST MODEL
# ---------------------------
best_name = max(results, key=lambda k: results[k]["acc"])
print(f"\nBest scaler: {best_name} ({results[best_name]['acc']:.4f})")

results[best_name]["model"].summary()

Class distribution: {0: 176, 1: 72, 2: 220}
Class weights: {0: 0.8863636363636364, 1: 2.1666666666666665, 2: 0.7090909090909091}

C:\Users\thakk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

MinMax      test accuracy: 0.7183

C:\Users\thakk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Standard    test accuracy: 0.2535

C:\Users\thakk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Robust      test accuracy: 0.2817

Best scaler: MinMax (0.7183)

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_18 (Dense)                │ (None, 64)             │         1,024 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_12          │ (None, 64)             │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_6 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_19 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_13          │ (None, 32)             │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_20 (Dense)                │ (None, 3)              │            99 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 10,379 (40.55 KB)

 Trainable params: 3,395 (13.26 KB)

 Non-trainable params: 192 (768.00 B)

 Optimizer params: 6,792 (26.54 KB)

In [63]:
from sklearn.metrics import classification_report, confusion_matrix

y_pred_cls = np.argmax(best["model"].predict(best["X_test"]), axis=1)

print(f"Results with {best_name} scaler\n")

print(classification_report(
    best["y_test"], y_pred_cls,
    target_names=["Class 0 (Low)", "Class 1 (Medium)", "Class 2 (High)"]
))

print("Confusion Matrix:")
print(confusion_matrix(best["y_test"], y_pred_cls))

3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
Results with MinMax scaler

                  precision    recall  f1-score   support

   Class 0 (Low)       0.63      0.70      0.67        27
Class 1 (Medium)       0.50      0.64      0.56        11
  Class 2 (High)       0.93      0.76      0.83        33

        accuracy                           0.72        71
       macro avg       0.69      0.70      0.69        71
    weighted avg       0.75      0.72      0.73        71

Confusion Matrix:
[[19  6  2]
 [ 4  7  0]
 [ 7  1 25]]